---
- name: Ensure Go app service is running
  service:
    name: "{{ go_app_service_name }}"
    state: started
    enabled: yes
  ignore_errors: yes
  register: goapp_status

- name: Display Go app service status
  debug:
    msg: "Go app service status: {{ goapp_status }}"

- name: Create systemd service template for Go app (optional)
  template:
    src: goapp.service.j2
    dest: "/etc/systemd/system/{{ go_app_service_name }}.service"
    backup: yes
  notify:
    - reload systemd
    - restart goapp

- name: Enable Go app service
  service:
    name: "{{ go_app_service_name }}"
    enabled: yes
